version: 0.2

phases:
  build:
    commands:
      - echo 빌드 시작...
      - chmod +x ./gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - echo 빌드 성공...!
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'